In [1]:
import torch
print(torch.__version__)

2.1.2


In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
# create tensor 
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
scalar.item()

7

In [7]:
# vector
vector = torch.tensor([10, 7])
vector

tensor([10,  7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
# matrix
matrix = torch.tensor([[7, 8],
                       [9, 10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
matrix.ndim

2

In [12]:
matrix.shape

torch.Size([2, 2])

In [16]:
# tensor
tensor1 = torch.tensor([[1, 2, 3],
                        [3, 5, 6],
                        [6, 8, 9]])
tensor1

tensor([[1, 2, 3],
        [3, 5, 6],
        [6, 8, 9]])

In [17]:
tensor1.ndim

2

In [18]:
tensor1.shape

torch.Size([3, 3])

In [20]:
tensor2 = torch.tensor([[[1, 2, 3],
                         [3, 5, 6],
                         [6, 8, 9]]])
tensor2

tensor([[[1, 2, 3],
         [3, 5, 6],
         [6, 8, 9]]])

In [21]:
tensor2.ndim

3

In [22]:
tensor2.shape

torch.Size([1, 3, 3])

In [7]:
# create a random tensor
random_tensor = torch.rand(size=(224, 224, 3))
random_tensor.shape, random_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [8]:
# create zeros
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [9]:
# create ones
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [11]:
# arange
zero_to_ten = torch.arange(0, 10, 1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
# create same shape tensor with another
ten_ones = torch.ones_like(input=zero_to_ten)
ten_zero = torch.zeros_like(input=zero_to_ten)
ten_ones, ten_zero

(tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
 tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]))

In [17]:
# dtype and device 
# pytorch like to caclulate with the same dtype and on same device
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,
                               device=None,
                               requires_grad=False) # if true, operations performed on the tensor are recorded
float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device 
# these 3 informations are always the things you want to get.

(torch.Size([3]), torch.float32, device(type='cpu'))

In [16]:
# use float16, we have to set the dtype
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16)
float_16_tensor.dtype

torch.float16

In [28]:
# manipulating tensor +-x/matrix
tensor = torch.tensor([1, 2, 3])
# tensor + 10
torch.add(tensor, 10)

tensor([11, 12, 13])

In [20]:
tensor - 10

tensor([-9, -8, -7])

In [27]:
# tensor * 10
torch.multiply(tensor, 10)

tensor([10, 20, 30])

In [22]:
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

In [23]:
tensor

tensor([1, 2, 3])

In [29]:
torch.mul(tensor, tensor)

tensor([1, 4, 9])

In [30]:
tensor.shape

torch.Size([3])

In [31]:
torch.matmul(tensor, tensor) # is faster than @

tensor(14)

In [32]:
tensor @ tensor

tensor(14)

In [34]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

tensor_A.shape, tensor_B.shape
# torch.matmul(tensor_A, tensor_B) # (this will error)

(torch.Size([3, 2]), torch.Size([3, 2]))

In [40]:
tensor = torch.matmul(tensor_A, tensor_B.T)

In [41]:
tensor.shape

torch.Size([3, 3])

In [42]:
torch.mm(tensor, tensor) # mm is short for matmul

tensor([[ 5694.,  6348.,  7002.],
        [12920., 14404., 15888.],
        [20146., 22460., 24774.]])

In [43]:
tensor

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [47]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input 
                         out_features=5) # out_features = describes outer value 
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[ 2.3290,  1.2658,  0.6529,  0.5820, -0.0732],
        [ 4.5841,  2.2336,  0.6284,  0.7241,  0.1360],
        [ 6.8391,  3.2014,  0.6039,  0.8661,  0.3452]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 5])


**Remember, matrix multiplication is all you need. Dimension is everywhere.**

In [50]:
# find min, max, mean, sum
x = torch.arange(0, 100, 10)
x 

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [51]:
x.min()

tensor(0)

In [52]:
x.max()

tensor(90)

In [53]:
x.sum()

tensor(450)

In [56]:
x.type(torch.float32).mean()  # must set the type to float32

tensor(45.)

In [57]:
# work as the same 
torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)

(tensor(90), tensor(0), tensor(45.), tensor(450))

In [58]:
# argmin, argmax
x.argmin(), x.argmax()

(tensor(0), tensor(9))

In [59]:
# change date type
tensor = torch.arange(10, 100, 5)
tensor.dtype

torch.int64

In [62]:
tensor_float32 = tensor.type(torch.float32)
tensor_float32

tensor([10., 15., 20., 25., 30., 35., 40., 45., 50., 55., 60., 65., 70., 75.,
        80., 85., 90., 95.])

In [63]:
tensor_float16 = tensor.type(torch.float16)
tensor_float16

tensor([10., 15., 20., 25., 30., 35., 40., 45., 50., 55., 60., 65., 70., 75.,
        80., 85., 90., 95.], dtype=torch.float16)

In [64]:
tensor_int8 = tensor_float16.type(torch.int8)
tensor_int8

tensor([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95],
       dtype=torch.int8)

**关于数据精度：关注数字越大，计算精度越高，数字越小，计算精度越低，但是速度越快，手机上就会用int8来处理**

In [66]:
# play with the dimensions of tensor
# reshape, stack, squeeze, unsqueeze
# create a tensor
tensor = torch.arange(1., 8.)
tensor, tensor.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [68]:
tensor_reshaped = tensor.reshape([1, 7])
tensor_reshaped, tensor_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [72]:
tensor_view = tensor.view(1, 1, 7)
tensor_view

tensor([[[1., 2., 3., 4., 5., 6., 7.]]])

In [73]:
# change the view will change the orignal tensor too
tensor_view[0][0][0] = 100
tensor

tensor([100.,   2.,   3.,   4.,   5.,   6.,   7.])

In [79]:
# stack tensor on top of each other
stacked_tensor = torch.stack([tensor, tensor, tensor], dim=1)
stacked_tensor

tensor([[100., 100., 100.],
        [  2.,   2.,   2.],
        [  3.,   3.,   3.],
        [  4.,   4.,   4.],
        [  5.,   5.,   5.],
        [  6.,   6.,   6.],
        [  7.,   7.,   7.]])

In [87]:
# stack tensor on top of each other
stacked_tensor = torch.stack([tensor, tensor, tensor], dim=0)
stacked_tensor, stacked_tensor.shape

(tensor([[100.,   2.,   3.,   4.,   5.,   6.,   7.],
         [100.,   2.,   3.,   4.,   5.,   6.,   7.],
         [100.,   2.,   3.,   4.,   5.,   6.,   7.]]),
 torch.Size([3, 7]))

In [83]:
tensor.ndim # tensor的堆叠方式是在那个方向上扩展，复制

1

In [94]:
# squeeze
tensor = torch.rand(1, 5)
print(tensor.shape)
tensor_squeezed = tensor.squeeze()
print(tensor_squeezed.shape)
tensor_squeezed

torch.Size([1, 5])
torch.Size([5])


tensor([0.2695, 0.3588, 0.1994, 0.5472, 0.0062])

In [96]:
tensor = tensor_squeezed.unsqueeze(dim=0)
tensor

tensor([[0.2695, 0.3588, 0.1994, 0.5472, 0.0062]])

In [97]:
tensor = tensor_squeezed.unsqueeze(dim=1)
tensor

tensor([[0.2695],
        [0.3588],
        [0.1994],
        [0.5472],
        [0.0062]])

In [103]:
tensor.shape # use permute to change the dim

torch.Size([1, 5])

In [104]:
tensor = tensor.permute(1, 0) 

In [105]:
tensor.shape

torch.Size([5, 1])

In [106]:
# index and slice in tensor is similar as numpy

In [110]:
# numpy --> tensor
import numpy as np
array = np.arange(1.0, 8.0)
print(array)
tensor = torch.from_numpy(array)
print(tensor) # default to be convert to float64 the same as numpy

[1. 2. 3. 4. 5. 6. 7.]
tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)


In [111]:
# tensor to numpy
new_array = tensor.numpy()
new_array

array([1., 2., 3., 4., 5., 6., 7.])

In [116]:
# random seed
torch.manual_seed(42)
random_tensor_1 = torch.rand(3, 4)
torch.manual_seed(42)
random_tensor_2 = torch.rand(3, 4)
random_tensor_1 == random_tensor_2
# false before set seed, the seed should be set twice for the two tensor

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [118]:
# !nvidia-smi

In [119]:
# Check for GPU
import torch
torch.cuda.is_available()

False

In [120]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [121]:
# Count number of devices
torch.cuda.device_count()

0

In [122]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3])

In [123]:
# Instead, copy the tensor back to cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])